### ISSUE TITLE
question

### ISSUE THREAD

**Issue by junyuseu** [KaimingHe/resnet-1k-layers#3]
@KaimingHe Referencing your paper (http://arxiv.org/abs/1603.05027) ,I reimplement the pre-activation unit of ResNet-110, also the baseline ResNet-110 in (http://arxiv.org/abs/1512.03385) with caffe. The baseline 's performance is pretty good, but the pre-activation unit is not. This is the network structure of pre-act ResNet-110: (http://ethereon.github.io/netscope/#/gist/41d6e48f15d1c0b154b499602fb4a529) Are there any problem?

**Comment by GuitarYourself** [comment]
@junyuseu did you solve your problem? I confront the same problem. when i replace with BN and pre-activation, the init learning rate must be much smaller and it is hard to converge.

**Comment by junyuseu** [comment]
I made some mistakes in the network structure when I try to use the pre-activation unit.When I fixed that,I got the good results the same as the paper did.
